services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5018:5018"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
